name: fpl_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  get_it: ^4.0.1
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.1+1
  modal_progress_hud: ^0.1.3
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: Varela Round
      fonts: 
        - asset: assets/fonts/VarelaRound-Regular.ttf

    


